#!/usr/bin/env bash
VENV_NAME=${1:-env}

if [ ! -d "$VENV_NAME" ]
then
    python3 -m venv "$VENV_NAME"
fi
# shellcheck source=/dev/null
source "$VENV_NAME/bin/activate"

# pip3 install -r requirements.txt

echo "Installing keras-contrib..."

pip3 install git+https://www.github.com/keras-team/keras-contrib.git

echo "Downloading spaCy english module..."

python3 -m spacy download en_core_web_sm